soybeanjs/soybean-admin-element-plus

src/styles/scss/element-plus.scss
style(styles): :lipstick: set transpatent bg for ElButton in dark theme
=> style(styles): :lipstick: set transpatent bg for ElButton in dark theme

src/views/home/index.vue, src/views/home/modules/header-banner.vue
style(styles): :lipstick: adjust home style
=> style(styles): :lipstick: adjust home style

src/App.vue
fix(projects): :bug: fix ElConfigProvider warning
=> fix(projects): :bug: fix ElConfigProvider warning

package.json
chore(other): :package: adjust package.json website
=> chore(other): :package: adjust package.json website

src/layouts/modules/global-tab/context-menu.vue
fix(projects): :bug: home tab disabled
=> fix(projects): :bug: home tab disabled

.env, src/router/guard/route.ts
refactor(projects): :recycle: sync refactor router guard.
=> refactor(projects): :recycle: sync refactor router guard.

src/layouts/modules/global-search/components/search-modal.vue
fix(projects): :bug: fix global-search input auto focus
=> fix(projects): :bug: fix global-search input auto focus

src/plugins/app.ts
feat(projects): :sparkles: sync support scheduled detection and update system.
=> feat(projects): :sparkles: sync support scheduled detection and update system.

build/plugins/router.ts, package.json, src/locales/langs/en-us.ts, src/locales/langs/zh-cn.ts, src/router/elegant/transform.ts, src/router/routes/index.ts, src/typings/elegant-router.d.ts
feat(projects): :sparkles: add link to ElementPlus document
=> feat(projects): :sparkles: add link to ElementPlus document

src/styles/scss/element-plus.scss
style(styles): :lipstick: adjust ElSubmenu margin-top
=> style(styles): :lipstick: adjust ElSubmenu margin-top

src/store/modules/route/index.ts
fix(projects): :bug: check if init userInfo when initAuthRoute
=> fix(projects): :bug: check if init userInfo when initAuthRoute

src/views/plugin/copy/index.vue
fix(projects): :bug: fix plugin/copy ElInputGroup warning
=> fix(projects): :bug: fix plugin/copy ElInputGroup warning

src/router/elegant/routes.ts
style(projects): :art: modify table icon in the menu
=> style(projects): :art: modify table icon in the menu

src/views/plugin/gantt/index.vue
fix(projects): :bug: fix gantt chart change
=> fix(projects): :bug: fix gantt chart change

src/views/alova/user/index.vue, src/views/manage/menu/index.vue, src/views/manage/role/index.vue, src/views/manage/user/index.vue
fix(projects): :bug: adjust the display of ElPagination total
=> fix(projects): :bug: adjust the display of ElPagination total

src/layouts/modules/global-header/components/user-avatar.vue, src/layouts/modules/global-header/index.vue, src/layouts/modules/global-tab/index.vue
style(styles): :lipstick: adjust the spacing between header button
=> style(styles): :lipstick: adjust the spacing between header button

src/views/alova/user/index.vue, src/views/manage/menu/index.vue, src/views/manage/role/index.vue, src/views/manage/user/index.vue, src/views/plugin/excel/index.vue
style(styles): :lipstick: fix table automatic height
=> style(styles): :lipstick: fix table automatic height

src/views/manage/role/modules/role-operate-drawer.vue
fix(projects): :bug: fix dialog can`t be closed in manage/role
=> fix(projects): :bug: fix dialog can`t be closed in manager/role

.vscode/settings.json
=> chore(other): :art: 格式化配置修改

.eslintrc, .gitattributes
chore(styles): :bug: add .gitattributes
=> chore(styles): :bug: add .gitattributes

.editorconfig
chore(styles): :wrench: sync add .editorconfig
=> chore(styles): :wrench: sync add .editorconfig

src/router/guard/route.ts, src/store/modules/auth/index.ts, src/store/modules/route/index.ts
fix(projects): :bug: check if init userInfo when initAuthRoute.
=> fix(projects): :bug: check if init userInfo when initAuthRoute.

.gitignore, .npmrc, .vscode/settings.json, vite.config.ts
chore(other): :bug: sync configuration
=> chore(other): :bug: sync configuration

src/layouts/modules/global-menu/modules/horizontal-menu.vue, src/layouts/modules/global-menu/modules/horizontal-mix-menu.vue, src/layouts/modules/global-menu/modules/reversed-horizontal-mix-menu.vue, src/layouts/modules/global-menu/modules/vertical-menu.vue, src/layouts/modules/global-menu/modules/vertical-mix-menu.vue
fix(projects): :bug: fix ElMenu ellipsis width full
=> fix(projects): :bug: fix ElMenu ellipsis width full

src/layouts/modules/global-header/index.vue
style(styles): :lipstick: fix the spacing between header button
=> style(styles): :lipstick: fix the spacing between header button

CHANGELOG.md, package.json, packages/alova/package.json, packages/axios/package.json, packages/color/package.json, packages/hooks/package.json, packages/materials/package.json, packages/ofetch/package.json, packages/scripts/package.json, packages/uno-preset/package.json, packages/utils/package.json, pnpm-lock.yaml, src/App.vue, src/layouts/modules/theme-drawer/modules/page-fun.vue, src/store/modules/theme/shared.ts, src/theme/settings.ts, src/typings/app.d.ts
:bookmark: sync release v1.3.10
=> :bookmark: sync release v1.3.10

src/layouts/modules/global-header/index.vue, src/layouts/modules/theme-drawer/modules/page-fun.vue, src/locales/langs/en-us.ts, src/locales/langs/zh-cn.ts, src/theme/settings.ts, src/typings/app.d.ts
feat(projects): :sparkles: multi language buttons support hiding
=> feat(projects): :sparkles: multi language buttons support hiding

src/hooks/common/router.ts, src/store/modules/auth/index.ts
fix(projects): :bug: fix login success notification.
=> fix(projects): :bug: fix login success notification.

package.json, pnpm-lock.yaml, src/styles/scss/global.scss
chore(deps): :arrow_up: update sass
=> chore(deps): :arrow_up: update sass

src/views/manage/menu/index.vue, src/views/manage/menu/modules/menu-operate-modal.vue, src/views/manage/role/index.vue, src/views/manage/role/modules/button-auth-modal.vue, src/views/manage/role/modules/menu-auth-modal.vue, src/views/manage/user-detail/[id].vue, src/views/manage/user/index.vue
style(projects): :art: fix eslint warning
=> style(projects): :art: fix eslint warning

build/config/cli-helper.ts, build/config/proxy.ts
ci(other): :sparkles: display the actual request url in terminal
=> ci(other): :sparkles: display the actual request url in terminal

src/constants/app.ts, src/plugins/loading.ts, src/store/modules/theme/index.ts, src/store/modules/theme/shared.ts, src/typings/storage.d.ts
feat(projects): :sparkles: support loading page dark mode adaptation
=> feat(projects): :sparkles: support loading page dark mode adaptation

src/layouts/modules/global-menu/modules/vertical-menu.vue
fix(projects): :bug: add Menu default-openeds.
=> fix(projects): :bug: add Menu default-openeds. fix [#57]

README.en_US.md, README.md
=> docs(projects): update README.
